spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related with production APIs "
  contactDetails:
    name: "Cristopher Vergara - Product Owner"
    email: "cristopher_vergara@mail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
